#!/usr/bin/env php
<?php

// A command-line test:
// bogart test=1 one --help -abc --test=true

require realpath(__DIR__).'/ClassLoader.php';
Bogart\ClassLoader::register();

$cli = new Bogart\Cli($argv);
$cli->run();
